### ISSUE TITLE
可以把网页显示的文本和ID做成某个颜色的高亮嘛，在浏览的时候一看颜色就知道ID在哪里了。

### ISSUE THREAD

**Issue by df13954** [lygttpod/AndroidAuto#1]
比如ID高亮，或者文本前面的提示语高亮等等。

**Comment by lygttpod** [comment]
试了下加高亮之后整个页面看起来比较凌乱，没有原版的清爽，你可以看下效果：
`ID和Text两种颜色`

![高亮多色](https://github.com/lygttpod/AndroidAuto/assets/11826777/98d9c17f-17ab-4941-b8a6-866556f24c20)

`ID和Text统一颜色`

![高亮单色](https://github.com/lygttpod/AndroidAuto/assets/11826777/3df1980e-8754-4064-86f5-84a1a4ead62a)

> ### 如果你有更好的配色方案可以提供一下，至少目前这种样式个人不太喜欢

**Comment by df13954** [comment]
> 试了下加高亮之后整个页面看起来比较凌乱，没有原版的清爽，你可以看下效果： `ID和Text两种颜色`
> 
> ![高亮多色](https://user-images.githubusercontent.com/11826777/263464187-98d9c17f-17ab-4941-b8a6-866556f24c20.png)
> 
> `ID和Text统一颜色`
> 
> ![高亮单色](https://user-images.githubusercontent.com/11826777/263464193-3df1980e-8754-4064-86f5-84a1a4ead62a.png)
> 
> > ### 如果你有更好的配色方案可以提供一下，至少目前这种样式个人不太喜欢

可以做成高亮颜色可配置嘛，这样默认不加高亮，在web页面可以填高亮颜色

**Comment by lygttpod** [comment]
@df13954 更新APP到v1.0.3即可体验到id和text高亮配置功能

**Comment by df13954** [comment]
> @df13954 更新APP到v1.0.3即可体验到id和text高亮配置功能

欧克欧克
