### ISSUE TITLE
小米11闹钟

### ISSUE THREAD

**Issue by luckWenTao** [lygttpod/AndroidAuto#2]
下拉状态栏有的时候会把闹钟关掉，因为通知栏里面闹钟的下方正好有关闭按钮
![image](https://github.com/lygttpod/AndroidAuto/assets/18210031/1a60aafe-e0b8-4a0d-b9a6-b1a2e8cb17f0)

**Comment by luckWenTao** [comment]
应该是启动一个应用，这个时候触发了检测，这个时候下拉状态栏就会关闭闹钟

**Comment by lygttpod** [comment]
@BigSweet 已修复，打开APP升级至1.0.6即可体验
