### ISSUE TITLE
build时报gbk错误

### ISSUE THREAD

**Issue by LingChen19950** [lygttpod/AndroidAuto#3]
![image](https://github.com/lygttpod/AndroidAuto/assets/82627767/1c8ea683-bb78-49f2-b238-ad23b40c64e0)
怀疑是jdk版本不兼容，但是怎么改都一样的报错

**Comment by lygttpod** [comment]
升级一下AGP版本试试

**Comment by LingChen19950** [comment]
![image](https://github.com/lygttpod/AndroidAuto/assets/82627767/17a19783-b40f-41bd-8fdf-c473d6642218)
8.1.2了，相同的报错

**Comment by LingChen19950** [comment]
![image](https://github.com/lygttpod/AndroidAuto/assets/82627767/898da22a-1643-4182-96d7-f72321712dd2)
还原了低版本编译通过
![image](https://github.com/lygttpod/AndroidAuto/assets/82627767/8327af69-9525-4aed-b750-16816447deee)
