### ISSUE TITLE
一直触发百度输入法

### ISSUE THREAD

**Issue by LingChen19950** [lygttpod/AndroidAuto#6]
百度输入法会频繁触发无障碍，然后因为锁的原因，导致正常的应用无法跳过。
com.baidu.input
测试手机华为mate 40 pro，鸿蒙4.0，百度输入法最新版

**Comment by lygttpod** [comment]
方便的话录一个视频或者截几张关键图我去跟踪做一下

**Comment by lygttpod** [comment]
请打开APP自动升级到新版本1.0.8

新增了是否禁用单个app检测广告的开关，可以设置禁止检测百度输入法App
